rbac:
  create: true
podSecurityPolicy:
  enabled: false
imagePullSecrets: []
serviceAccounts:
  server:
    create: true
    name: ''
    annotations: {}
    automountServiceAccountToken: true
commonMetaLabels: {}
configmapReload:
  reloadUrl: ''
  env: []
  prometheus:
    enabled: true
    name: configmap-reload
    image:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.71.2
      digest: ''
      pullPolicy: IfNotPresent
    extraArgs: {}
    extraVolumeDirs: []
    extraVolumeMounts: []
    extraConfigmapMounts: []
    containerSecurityContext: {}
    resources: {}
server:
  name: server
  clusterRoleNameOverride: ''
  releaseNamespace: false
  sidecarContainers: {}
  sidecarTemplateValues: {}
  image:
    repository: quay.io/prometheus/prometheus
    tag: ''
    digest: ''
    pullPolicy: IfNotPresent
  command: []
  priorityClassName: ''
  enableServiceLinks: true
  prefixURL: ''
  baseURL: ''
  env: []
  defaultFlagsOverride: []
  extraFlags:
  - web.enable-lifecycle
  configPath: /etc/config/prometheus.yml
  storagePath: ''
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
  remoteWrite: []
  remoteRead: []
  tsdb: {}
  exemplars: {}
  probeHeaders: []
  extraArgs: {}
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  extraHostPathMounts: []
  extraConfigmapMounts: []
  extraSecretMounts: []
  configMapOverrideName: ''
  extraConfigmapLabels: {}
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: prometheus.schlafdata.cloud
      nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: prometheus
    ingressClassName: nginx-internal
    hosts:
    - prometheus.schlafdata.cloud
    paths:
    - /
    tls:
    - secretName: wildcard-tls-cert-schlafdata-cloud
      hosts:
      - prometheus.schlafdata.cloud
  strategy:
    type: Recreate
  hostAliases: []
  tolerations: []
  nodeSelector: {}
  affinity: {}
  podAntiAffinity: ''
  podAntiAffinityTopologyKey: kubernetes.io/hostname
  topologySpreadConstraints: []
  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1
  persistentVolume:
    enabled: true
    statefulSetNameOverride: ''
    accessModes:
    - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ''
    mountPath: /data
    size: 8Gi
    subPath: ''
  emptyDir:
    sizeLimit: ''
  podAnnotations: {}
  podLabels: {}
  alertmanagers: []
  podSecurityPolicy:
    annotations: {}
  replicaCount: 1
  revisionHistoryLimit: 10
  configMapAnnotations: {}
  deploymentAnnotations: {}
  statefulSet:
    enabled: false
  tcpSocketProbeEnabled: false
  probeScheme: HTTP
  readinessProbeInitialDelay: 30
  readinessProbePeriodSeconds: 5
  readinessProbeTimeout: 4
  readinessProbeFailureThreshold: 3
  readinessProbeSuccessThreshold: 1
  livenessProbeInitialDelay: 30
  livenessProbePeriodSeconds: 15
  livenessProbeTimeout: 10
  livenessProbeFailureThreshold: 3
  livenessProbeSuccessThreshold: 1
  startupProbe:
    enabled: false
    periodSeconds: 5
    failureThreshold: 30
    timeoutSeconds: 10
  resources: {}
  hostNetwork: false
  dnsPolicy: ClusterFirst
  portName: ''
  verticalAutoscaler:
    enabled: false
  dnsConfig: {}
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
  containerSecurityContext: {}
  service:
    annotations: {}
    labels: {}
    clusterIP: ''
    port: 9090
    targetPort: 9090
    externalIPs: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    type: ClusterIP
    additionalPorts: []
    publishNotReadyAddresses: false
    sessionAffinity: None
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
  terminationGracePeriodSeconds: 300
  retention: 15d
  retentionSize: ''
ruleFiles: {}
scrapeConfigFiles: []
serverFiles:
  alerting_rules.yml: {}
  alerts: {}
  recording_rules.yml: {}
  rules: {}
  prometheus.yml:
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: kubernetes-apiservers
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        action: keep
        regex: default;kubernetes;https
    - job_name: kubernetes-nodes
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels:
        - __meta_kubernetes_node_name
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics
    - job_name: kubernetes-nodes-cadvisor
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels:
        - __meta_kubernetes_node_name
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      metric_relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - action: replace
        source_labels:
        - id
        regex: ^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$
        target_label: rkt_container_name
        replacement: ${2}-${1}
      - action: replace
        source_labels:
        - id
        regex: ^/system\.slice/(.+)\.service$
        target_label: systemd_service_name
        replacement: ${1}
    - job_name: kubernetes-service-endpoints
      honor_labels: true
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
        action: keep
        regex: true
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
        action: drop
        regex: true
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        action: replace
        target_label: __address__
        regex: (.+?)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        action: replace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        action: replace
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_node_name
        action: replace
        target_label: node
    - job_name: kubernetes-service-endpoints-slow
      honor_labels: true
      scrape_interval: 5m
      scrape_timeout: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
        action: keep
        regex: true
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        action: replace
        target_label: __address__
        regex: (.+?)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        action: replace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        action: replace
        target_label: service
      - source_labels:
        - __meta_kubernetes_pod_node_name
        action: replace
        target_label: node
    - job_name: prometheus-pushgateway
      honor_labels: true
      kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
        action: keep
        regex: pushgateway
    - job_name: kubernetes-services
      honor_labels: true
      metrics_path: /probe
      params:
        module:
        - http_2xx
      kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
        action: keep
        regex: true
      - source_labels:
        - __address__
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox
      - source_labels:
        - __param_target
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: service
    - job_name: kubernetes-pods
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        action: keep
        regex: true
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
        action: drop
        regex: true
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        action: replace
        regex: (https?)
        target_label: __scheme__
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        action: replace
        regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        action: replace
        regex: (\d+);((([0-9]+?)(\.|$)){4})
        replacement: $2:$1
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        action: replace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_name
        action: replace
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_phase
        regex: Pending|Succeeded|Failed|Completed
        action: drop
      - source_labels:
        - __meta_kubernetes_pod_node_name
        action: replace
        target_label: node
    - job_name: kubernetes-pods-slow
      honor_labels: true
      scrape_interval: 5m
      scrape_timeout: 30s
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: replace
        target_label: cluster
        replacement: cluster-01
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
        action: keep
        regex: true
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        action: replace
        regex: (https?)
        target_label: __scheme__
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        action: replace
        regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        target_label: __address__
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        action: replace
        regex: (\d+);((([0-9]+?)(\.|$)){4})
        replacement: $2:$1
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        action: replace
        target_label: namespace
      - source_labels:
        - __meta_kubernetes_pod_name
        action: replace
        target_label: pod
      - source_labels:
        - __meta_kubernetes_pod_phase
        regex: Pending|Succeeded|Failed|Completed
        action: drop
      - source_labels:
        - __meta_kubernetes_pod_node_name
        action: replace
        target_label: node
    - job_name: gpu-metrics
      scrape_interval: 1s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kube-system
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        action: replace
        target_label: kubernetes_node
extraScrapeConfigs: ''
alertRelabelConfigs: {}
networkPolicy:
  enabled: false
forceNamespace: ''
extraManifests: []
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
