namespace: default
aws:
  region: us-west-2
interval: 5m
logLevel: debug
logFormat: json
policy: sync
registry: txt
txtOwnerId: ZJQT16387AFJE3BZAM309
replicas: 1
rbac:
  create: true
  serviceAccountName: external-dns
  serviceAccountAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::406622241617:policy/external-dns
  apiVersion: v1
  pspEnabled: false
securityContext:
  fsGroup: 65534
volumes:
- name: token-vol
  projected:
    sources:
    - serviceAccountToken:
        path: token
resources: {}
